version: '3.8'

services:
  nginx:
    image: nginx:stable
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./ssl:/etc/nginx/ssl
      # - ./ssl.conf:/etc/nginx/ssl.conf:ro
    ports:
      - 80:80
      # - 443:443
    depends_on:
      - flaskapp
    command: >
      /bin/bash -c "rm -f /etc/nginx/conf.d/default.conf &&
                    nginx -g 'daemon off;'"
    networks:
      - bookstore_net

  flaskapp:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - bookstore_net

networks:
  bookstore_net:
